(CONT-256) Removing outdated code
puppetlabs/puppetlabs-firewall pull request #1084
Opened 2022-11-03 12:27 UTC by LukasAud

Prior to this commit, the firewall modules had multiple instances of outdated code.

This commit aims to clean-up some of that code to keep the module clean and readable.

2022-11-03 14:20 UTC, david22swan requested changes
Oe small comment and a syntax fix.
Otherwise looks good

2022-11-03 14:20 UTC, david22swan commented on manifests/linux/debian.pp
> -  if $package_name {
You still need the `if $package_name`

2022-11-03 15:16 UTC, LukasAud commented on manifests/linux/debian.pp
> -  if $package_name {
re-implemented

2022-11-04 16:43 UTC, david22swan approved these changes
LGTM

2022-11-04 16:43 UTC, merged